root: true
extends:
  - prettier
plugins:
  - prettier
settings:
  react:
    version: detect
parserOptions:
  ecmaVersion: latest
  ecmaFeatures:
    jsx: true
  sourceType: module
rules:
  prettier/prettier: error
  no-unused-vars: off
